version: '2'
services:
  kafka:
    image: spotify/kafka:latest
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
      - "2181:2181"
    environment:
      ADVERTISED_HOST: kafka
      ADVERTISED_PORT: 9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  pim-aggregator:
    image: pim-aggregator:latest
    build:
        context: .
        dockerfile: Dockerfile
    container_name: pim-aggregator
    links:
      - kafka:kafka
    ports:
      - "8081:8081"
    depends_on:
      - kafka
